apiVersion: apps/v1
kind: Deployment
metadata:
  name: dolesewonderlandfx-auth
  labels:
    app: dolesewonderlandfx-auth
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dolesewonderlandfx-auth
  template:
    metadata:
      labels:
        app: dolesewonderlandfx-auth
        component: backend
    spec:
      containers:
      - name: auth
        image: registry.digitalocean.com/dolesewonderlandfx-dev/auth:latest
        ports:
        - containerPort: 8002
          name: http
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: database_url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: jwt_secret
        - name: ENVIRONMENT
          value: "production"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 5
          periodSeconds: 5
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      imagePullSecrets:
      - name: ecr-secret