apiVersion: apps/v1
kind: Deployment
metadata:
  name: dolesewonderlandfx-email
  labels:
    app: dolesewonderlandfx-email
    component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dolesewonderlandfx-email
  template:
    metadata:
      labels:
        app: dolesewonderlandfx-email
        component: backend
    spec:
      containers:
      - name: email
        image: dolesewonderlandfx/email:latest
        ports:
        - containerPort: 8006
          name: http
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: database_url
        - name: SMTP_SERVER
          valueFrom:
            secretKeyRef:
              name: email-config
              key: smtp_server
        - name: SMTP_PORT
          valueFrom:
            secretKeyRef:
              name: email-config
              key: smtp_port
        - name: SMTP_USERNAME
          valueFrom:
            secretKeyRef:
              name: email-config
              key: smtp_username
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: email-config
              key: smtp_password
        - name: FROM_EMAIL
          valueFrom:
            secretKeyRef:
              name: email-config
              key: from_email
        - name: ENVIRONMENT
          value: "production"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8006
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8006
          initialDelaySeconds: 5
          periodSeconds: 5
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      imagePullSecrets:
      - name: ecr-secret