apiVersion: apps/v1
kind: Deployment
metadata:
  name: dolesewonderlandfx-paper-trading
  labels:
    app: dolesewonderlandfx-paper-trading
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dolesewonderlandfx-paper-trading
  template:
    metadata:
      labels:
        app: dolesewonderlandfx-paper-trading
        component: backend
    spec:
      containers:
      - name: paper-trading
        image: registry.digitalocean.com/dolesewonderlandfx-dev/paper-trading:latest
        ports:
        - containerPort: 8005
          name: http
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: database_url
        - name: ENVIRONMENT
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8005
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8005
          initialDelaySeconds: 5
          periodSeconds: 5
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      imagePullSecrets:
      - name: ecr-secret