apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: dolesewonderlandfx-prometheus
    component: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    rule_files:
      # - "first_rules.yml"
      # - "second_rules.yml"

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'api-service'
        static_configs:
          - targets: ['dolesewonderlandfx-api:8000']
        scrape_interval: 5s
        metrics_path: '/metrics'

      - job_name: 'auth-service'
        static_configs:
          - targets: ['dolesewonderlandfx-auth:8002']
        scrape_interval: 5s
        metrics_path: '/metrics'

      - job_name: 'ai-pipeline-service'
        static_configs:
          - targets: ['dolesewonderlandfx-ai-pipeline:8003']
        scrape_interval: 5s
        metrics_path: '/metrics'

      - job_name: 'insight-generator-service'
        static_configs:
          - targets: ['dolesewonderlandfx-insight-generator:8004']
        scrape_interval: 5s
        metrics_path: '/metrics'

      - job_name: 'backtester-service'
        static_configs:
          - targets: ['dolesewonderlandfx-backtester:8001']
        scrape_interval: 5s
        metrics_path: '/metrics'

      - job_name: 'paper-trading-service'
        static_configs:
          - targets: ['dolesewonderlandfx-paper-trading:8005']
        scrape_interval: 5s
        metrics_path: '/metrics'

      - job_name: 'social-trading-service'
        static_configs:
          - targets: ['dolesewonderlandfx-social-trading:8007']
        scrape_interval: 5s
        metrics_path: '/metrics'

      - job_name: 'email-service'
        static_configs:
          - targets: ['dolesewonderlandfx-email:8006']
        scrape_interval: 5s
        metrics_path: '/metrics'