global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-service'
    static_configs:
      - targets: ['api:8000']
    scrape_interval: 5s
    metrics_path: '/metrics'

  - job_name: 'backtester-service'
    static_configs:
      - targets: ['backtester:8001']
    scrape_interval: 5s
    metrics_path: '/metrics'

  - job_name: 'app-frontend'
    static_configs:
      - targets: ['app-frontend:3000']
    scrape_interval: 30s

  - job_name: 'web-landing'
    static_configs:
      - targets: ['web-landing:3000']
    scrape_interval: 30s

  - job_name: 'instructor-portal'
    static_configs:
      - targets: ['instructor-portal:3000']
    scrape_interval: 30s