name: CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push API service
      uses: docker/build-push-action@v5
      with:
        context: ./services/api
        push: true
        tags: dolesewonderlandfx/api:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push Backtester service
      uses: docker/build-push-action@v5
      with:
        context: ./services/backtester
        push: true
        tags: dolesewonderlandfx/backtester:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Deploy to production
      run: |
        echo "Deploying to production environment"
        # Add your deployment commands here
        # Example: kubectl apply -f k8s/ or docker-compose up -d on remote server